version: '3.7'

services:
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
